#include <stdio.h>                                                                                                                                                                                       
#include <stdlib.h>                                                                                                                                                                                      
#include <time.h>                                                                                                                                                                                        
                                                                                                                                                                                                         
//Dilraj Sooch 8888708                                                                                                                                                                                   
//Data Struct Assignment 2 Binary Tree                                                                                                                                                                   
/* Starting from an empty project, you must:                                                                                                                                                             
                                                                                                                                                                                                         
   Implement a set of C functions for Binary Search Trees. These functions should be implemented in their own .c file. The minimum set of functions required are (if you wish to create more functions ba
    Insert                                                                                                                                                                                               
                                                                                                                                                                                                         
   Search                                                                                                                                                                                                
   Count Nodes                                                                                                                                                                                           
   Determine Tree Height                                                                                                                                                                                 
   Write a main.c file which:                                                                                                                                                                            
   Inserts a random number of chars (from 11 to 20 chars, inclusive) into the tree. Each char can range from lowercase a to lowercase z.                                                                 
   Print out the all the chars inserted into the tree, in sorted alphabetical order.                                                                                                                     
   Print the number of nodes in the tree.                                                                                                                                                                
   Print the tree height                                                                                                                                                                                 
   */                                                                                                                                                                                                    
                                                                                                                                                                                                         
struct TreeNode {               //treenode struct                                                                                                                                                        
    char data;                                                                                                                                                                                           
    struct TreeNode *left, *right;                                                                                                                                                                       
};                                                                                                                                                                                                       
                                                                                                                                                                                                         
// Function to create a new tree node                                                                                                                                                                    
struct TreeNode* createNode(char data) {                                                                                                                                                                 
    struct TreeNode* newNode = (struct TreeNode*)malloc(sizeof(struct TreeNode));                                                                                                                        
    if (newNode == NULL) {                  //memory check criteria                                                                                                                                      
        printf("Memory allocation failed");                                                                                                                                                              
        exit(EXIT_FAILURE);                                                                                                                                                                              
    }                                                                                                                                                                                                    
    newNode->data = data;                                                                                                                                                                                
    newNode->left = newNode->right = NULL;          //tip of tree init                                                                                                                                   
    return newNode;                                                                                                                                                                                      
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
// Function to insert a node into BST                                                                                                                                                                    
struct TreeNode* insert(struct TreeNode* root, char data) {                                                                                                                                              
    if(root == NULL) {                                                                                                                                                                                   
        return createNode(data);        //if nothing in tree create tree level 1                                                                                                                         
    }                                                                                                                                                                                                    
    if(data <= root->data)                                                                                                                                                                               
        root->left = insert(root->left, data);        //inserting sort                                                                                                                                   
    else                                                                                                                                                                                                 
        root->right = insert(root->right, data);                                                                                                                                                         
                                                                                                                                                                                                         
    return root;                                                                                                                                                                                         
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
// Function to count nodes in BST                                                                                                                                                                        
int countNodes(struct TreeNode* root) {                                                                                                                                                                  
    if (root == NULL)                                                                                                                                                                                    
        return 0;   //terminating case                                                                                                                                                                   
    else                                                                                                                                                                                                 
        return (1 + countNodes(root->left) + countNodes(root->right));        //recursive code  1 is tip +how many nodes there are on                                                                    
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
// Function to determine the height of BST                                                                                                                                                               
int height(struct TreeNode* root) {                                                                                                                                                                      
    if (root == NULL)                                                                                                                                                                                    
        return -1;                                          //return -1 because subtracring 1 from level                                                                                                 
                                                                                                                                                                                                         
    int leftHeight = height(root->left);                                                                                                                                                                 
    int rightHeight = height(root->right);                                                                                                                                                               
                                                                                                                                                                                                         
    return (leftHeight > rightHeight) ? (leftHeight + 1) : (rightHeight + 1);       //whatever is longer you add 1 to leftheight or rightheight and                                                      
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
void inorderTraversal(struct TreeNode* root) {              //recursively traverses through left subtree and prints nodes  because left<right                                                            
    if (root != NULL) {                                                                                                                                                                                  
        inorderTraversal(root->left);                                                                                                                                                                    
        printf("%c ", root->data);                                                                                                                                                                       
                                                                                                                                                                                                         
        inorderTraversal(root->right);      //prints subtree in an ordered way                                                                                                                           
                                                                                                                                                                                                         
                                                                                                                                                                                                         
                                                                                                                                                                                                         
    }                                                                                                                                                                                                    
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
int main() {                                                                                                                                                                                             
    srand(time(NULL)); //seed                                                                                                                                                                            
                                                                                                                                                                                                         
    struct TreeNode *root = NULL;                                                                                                                                                                        
                                                                                                                                                                                                         
    int numberOfChars = rand() % 10 + 11; // Generate random number of chars between 11 and 20                                                                                                           
    printf("Number of chars to insert: %d\n", numberOfChars);                                                                                                                                            
                                                                                                                                                                                                         
    char characters[numberOfChars];                                                                                                                                                                      
    printf("Chars inserted into the tree: ");                                                                                                                                                            
    for (int i = 0; i < numberOfChars; i++) {                                                                                                                                                            
        characters[i] = 'a' + rand() % 26; // Generate random lowercase char                                                                                                                             
        printf("%c ", characters[i]);                                                                                                                                                                    
    }                                                                                                                                                                                                    
    printf("\n");                                                                                                                                                                                        
                                                                                                                                                                                                         
                                                                                                                                                                                                         
                                                                                                                                                                                                         
    // Sorting the characters array alphabetically                                                                                                                                                       
    for (int i = 0; i < numberOfChars - 1; i++) {               //alphabet sorting algo using bubble sort, goes through array multiple times, it                                                         
        for (int j = i + 1; j < numberOfChars; j++) {                                                                                                                                                    
            if (characters[i] > characters[j]) {                                                                                                                                                         
                char temp = characters[i];                                                                                                                                                               
                characters[i] = characters[j];                                                                                                                                                           
                characters[j] = temp;                                                                                                                                                                    
            }                                                                                                                                                                                            
        }                                                                                                                                                                                                
    }                                                                                                                                                                                                    
                                                                                                                                                                                                         
                                                                                                                                                                                                         
    // Inserting sorted characters into the BST                                                                                                                                                          
    for (int i = 0; i < numberOfChars; i++) {                                                                                                                                                            
        root = insert(root, characters[i]);                                                                                                                                                              
    }                                                                                                                                                                                                    
                                                                                                                                                                                                         
    printf("Alphabetically Arranged Order: ") ;                                                                                                                                                          
    inorderTraversal(root); // Print the characters in sorted order                                                                                                                                      
                                                                                                                                                                                                         
                                                                                                                                                                                                         
    printf("\n");                                                                                                                                                                                        
                                                                                                                                                                                                         
    printf("Number of nodes in the tree: %d\n", countNodes(root));                                                                                                                                       
    printf("Height of the tree: %d\n", height(root));                                                                                                                                                    
                                                                                                                                                                                                         
    return 0;                                                                                                                                                                                            
}                                                                                                                                                                                                        
                                                                                                                                                                                                         
